/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Restaurant extends ReviewableBusiness {
    // Attributes
    public String price;

    // Constructors
    public Restaurant(String name, double stars, String price) {
        this.name = name;
        this.stars = stars;
        this.price = price;
        this.reviews = new ArrayList<Review>();
    }

    // Methods
    public String toString(){
        return ("Restaurant name: " + this.name + " Stars: " + this.stars + " Price: " + this.price + "\n" + reviews.toString());
    }
}


