/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Restaurant {
    public static void main(String[] args) {
        Restaurant testaurant = new Restaurant("testaurant", 3, "$$");
        testaurant.addReview(new Review("Bubbles", "Decent", 5));
        testaurant.addReview(new Review("Bubbles", "Decent", 3));
        System.out.println(testaurant.toString());
    }
    // Attributes
    public String name;
    public double stars;
    public String price;
    public ArrayList<Review> reviews;

    // Constructors
    public Restaurant(String name, double stars, String price) {
        this.name = name;
        this.stars = stars;
        this.price = price;
        this.reviews = new ArrayList<Review>();
    }
    
    public void addReview(Review r) {
        this.reviews.add(r);
        this.updateStars();
    }
    
    public void updateStars() {
        double starcount = 0;
        for (Review rev: this.reviews) {
            starcount += rev.stars;
        }
        this.stars = (starcount/(this.reviews.size()));
    }

    // Methods
    public String toString(){
        //System.out.println("Restaurant name: " + this.name + " Stars: " + this.stars + " Price: " + this.price + "\n" + reviews.toString());
        return ("Restaurant name: " + this.name + " Stars: " + this.stars + " Price: " + this.price + "\n" + reviews.toString());
    }
}


