/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;

public class App {

    public static void main(String[] args) {
        linterFile("path goes here ");
    }
    public static void linterFile(String path) {
        int lineCount = 0;
        String line;
        try {
            Scanner scanner = new Scanner(new File(path));
            while (scanner.hasNextLine()) {
                lineCount++;
                line = scanner.nextLine();
                if(line.length() == 1 || line.length() == 0) {
                    continue;
                }
                else if(line.charAt(line.length()-1) != ';') {
                    if(line.contains("if") || line.contains("else")) {
                        continue;
                    }
                    else if(line.charAt(line.length()-1) == '{' || line.charAt(line.length()-1) == '}') {
                        continue;
//                        System.out.println("Line " + lineCount + ": Missing '{' or '}' ");
                    }
                    else {
                        System.out.println("Line " + lineCount + ": Missing semi-colon");
                    }
                }
            }
            scanner.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
