/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testRestaurantConstruct() {
        Restaurant testaurant = new Restaurant("testaurant", 5, "$$");
        assertEquals("testaurant", "testaurant", testaurant.name);
        assertEquals("5", 5, testaurant.stars, .00005);
        assertEquals("$$", "$$", testaurant.price);
        //assertTrue("Expected 'Restaurant name: testaurant Stars: 5 Price: $$' ", testaurant.toString().equals("Restaurant name: testaurant Stars: 5 Price: $$"));
    }

    @Test public void testReviewconstuct() {
        Review testRev = new Review("Bubbles", "Decent", 5);
        assertEquals("Bubbles", "Bubbles", testRev.author);
        assertEquals("Decent", "Decent", testRev.body);
        assertEquals("5", 5, testRev.stars, .00005);
    }

    @Test public void testAddReview() {
        Restaurant testaurant = new Restaurant("testaurant", 5, "$$");
        Review testRev = new Review("Bubbles", "Decent", 5);
        testaurant.addReview(testRev);
        assertEquals("Bubbles","Bubbles", testaurant.reviews.get(0).author);
        assertEquals("5",5, testaurant.reviews.get(0).stars, .00005);
        assertEquals("Decent","Decent", testaurant.reviews.get(0).body);
    }

    @Test public void testStars() {
        Restaurant testaurant = new Restaurant("testaurant", 3, "$$");
        assertEquals("5", 5, testaurant.stars, .00005);
        testaurant.addReview(new Review("Bubbles", "Decent", 5));
        testaurant.addReview(new Review("Julian", "I've got a plan to make this big bubs", 3));
        assertEquals("4.0", 4.0, testaurant.stars, .00005);
    }
}
